[custom]
; Clash 模板
ruleset=🍎 Apple,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=🔷 微软,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Microsoft.list
ruleset=☁️ Cloudflare直连,https://gist.githubusercontent.com/hanmoya176/b09a89cc43e603b933344d45a6a3289a/raw/cloudflare.list
ruleset=🎯 国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 国内直连,[]GEOIP,CN
ruleset=🎯 国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 国内直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/MI.list
ruleset=🎬 Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🎬 Disney+,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/DisneyPlus.list
ruleset=🎬 YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎬 HBO,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/HBO.list
ruleset=🎬 Amazon,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Amazon.list
ruleset=✈️ Telegram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Telegram.list
ruleset=🤖 ChatGPT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=🤖 Claude,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Claude.list
ruleset=🤖 Gemini,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Gemini.list
ruleset=🎵 Spotify,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Spotify.list
ruleset=📱 TikTok,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TikTok.list
ruleset=🔍 Google,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
ruleset=🐙 Github,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Github.list
ruleset=🐦 Twitter,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Twitter.list
ruleset=🚀 节点选择,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]♾️ 自动选择`.*
custom_proxy_group=♾️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`3600,,70
custom_proxy_group=🍎 Apple`select`[]DIRECT
custom_proxy_group=🔷 微软`select`[]DIRECT
custom_proxy_group=☁️ Cloudflare直连`select`[]DIRECT
custom_proxy_group=🎯 国内直连`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🎬 Netflix`select`.*`.*
custom_proxy_group=🎬 Disney+`select`.*`.*
custom_proxy_group=🎬 YouTube`select`[]♾️ 自动选择`[]🚀 节点选择`.*
custom_proxy_group=🎬 HBO`select`.*`.*
custom_proxy_group=🎬 Amazon`select`.*`.*
custom_proxy_group=✈️ Telegram`select`[]♾️ 自动选择`[]🚀 节点选择`.*
custom_proxy_group=🤖 ChatGPT`select`[]♾️ 自动选择`[]🚀 节点选择`.*
custom_proxy_group=🤖 Claude`select`[]♾️ 自动选择`[]🚀 节点选择`.*
custom_proxy_group=🤖 Gemini`select`[]♾️ 自动选择`[]🚀 节点选择`.*
custom_proxy_group=🎵 Spotify`select`[]♾️ 自动选择`[]🚀 节点选择`.*
custom_proxy_group=📱 TikTok`select`[]♾️ 自动选择`[]🚀 节点选择`.*
custom_proxy_group=🔍 Google`select`[]♾️ 自动选择`[]🚀 节点选择`.*
custom_proxy_group=🐙 Github`select`[]♾️ 自动选择`[]🚀 节点选择`.*
custom_proxy_group=🐦 Twitter`select`[]♾️ 自动选择`[]🚀 节点选择`.*

enable_rule_generator=true

[dns]
enable=true
default-nameserver=[223.5.5.5, 119.29.29.29]
nameserver=[https://dns.alidns.com/dns-query, https://sm2.doh.pub/dns-query]
fallback=[https://cloudflare-dns.com/dns-query, 8.8.8.8]
fallback-filter={geoip=true, ipcidr=[240.0.0.0/4]}
nameserver-policy={"geosite:apple": "https://dns.alidns.com/dns-query"}
